name: abstractions
description: Interfaces implemented in the percepts and used as types in apps using perception.
version: 0.0.0-a1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.10.0

  types_for_auth:
    git: https://github.com/enspyrco/types_for_auth
  json_utils:
    git: https://github.com/enspyrco/json_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  enspyr_lints:
    git: https://github.com/enspyrco/enspyr_lints